import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: {
    default: "NYT Best Sellers",
    template: "%s | NYT Best Sellers",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="retro">
      <body>
        <Header />
        <main className="max-w-screen-xl mx-auto px-4 md:px-6 py-6 md:py-12">
          {children}
        </main>
      </body>
    </html>
  );
}
